=== LittlePlanlessFool/ENG_Kurswahl/kurse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="kurse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurs" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="leistungskurs1" type="xs:string"/>
                            <xs:element name="leistungskurs2" type="xs:string"/>
                            <xs:element name="prüfungsfach3" type="xs:string"/>
                            <xs:element name="prüfungsfach4" type="xs:string"/>
                            <xs:element name="prüfungskomponente5" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="size" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LittlePlanlessFool/ENG_Kurswahl/kurse.xml
<?xml version="1.0" encoding="UTF-8"?>
<kurse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="kurse.xsd" size="112">
    <kurs id="1a">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>AFII</prüfungsfach3>
        <prüfungsfach4>MATHEMATIK</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>
    <kurs id="1b">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>AFII</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>MATHEMATIK</prüfungskomponente5>
    </kurs>
    <kurs id="1c">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>AFII</prüfungsfach4>
        <prüfungskomponente5>MATHEMATIK</prüfungskomponente5>
    </kurs>
    <kurs id="1d">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>MATHEMATIK</prüfungsfach4>
        <prüfungskomponente5>AFII + PHILOSOPHIE</prüfungskomponente5>
    </kurs>
    <kurs id="1e">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>MATHEMATIK</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>AFII + PHILOSOPHIE</prüfungskomponente5>
    </kurs>
    <kurs id="1f">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>MATHEMATIK</prüfungsfach3>
        <prüfungsfach4>AFII</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>

    <kurs id="2a">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>AFII</prüfungsfach3>
        <prüfungsfach4>NW</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>
    <kurs id="2b">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>AFII</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>NW</prüfungskomponente5>
    </kurs>
    <kurs id="2c">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>AFII</prüfungsfach4>
        <prüfungskomponente5>NW</prüfungskomponente5>
    </kurs>
    <kurs id="2d">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>NW</prüfungsfach4>
        <prüfungskomponente5>AFII + PHILOSOPHIE</prüfungskomponente5>
    </kurs>
    <kurs id="2e">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>NW</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>AFII + PHILOSOPHIE</prüfungskomponente5>
    </kurs>
    <kurs id="2f">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>NW</prüfungsfach3>
        <prüfungsfach4>AFII</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>

    <kurs id="3a">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>AFII</prüfungsfach3>
        <prüfungsfach4>INFORMATIK</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>
    <kurs id="3b">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>AFII</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>INFORMATIK</prüfungskomponente5>
    </kurs>
    <kurs id="3c">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>AFII</prüfungsfach4>
        <prüfungskomponente5>INFORMATIK</prüfungskomponente5>
    </kurs>
    <kurs id="3d">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>INFORMATIK</prüfungsfach4>
        <prüfungskomponente5>AFII + PHILOSOPHIE</prüfungskomponente5>
    </kurs>
    <kurs id="3e">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>INFORMATIK</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>AFII + PHILOSOPHIE</prüfungskomponente5>
    </kurs>
    <kurs id="3f">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>DEUTSCH</leistungskurs2>
        <prüfungsfach3>INFORMATIK</prüfungsfach3>
        <prüfungsfach4>AFII</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>

    <kurs id="10a">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>DEUTSCH</prüfungsfach3>
        <prüfungsfach4>NW</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>
    <kurs id="10b">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>DEUTSCH</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>NW</prüfungskomponente5>
    </kurs>
    <kurs id="10c">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>DEUTSCH</prüfungsfach4>
        <prüfungskomponente5>NW</prüfungskomponente5>
    </kurs>
    <kurs id="10d">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>MATHEMATIK</prüfungsfach3>
        <prüfungsfach4>NW</prüfungsfach4>
        <prüfungskomponente5>DEUTSCH</prüfungskomponente5>
    </kurs>
    <kurs id="10e">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>NW</prüfungsfach3>
        <prüfungsfach4>MATHEMATIK</prüfungsfach4>
        <prüfungskomponente5>DEUTSCH</prüfungskomponente5>
    </kurs>
    <kurs id="10f">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>NW</prüfungsfach3>
        <prüfungsfach4>DEUTSCH</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>

    <kurs id="11a">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>DEUTSCH</prüfungsfach3>
        <prüfungsfach4>INFORMATIK</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>
    <kurs id="11b">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>DEUTSCH</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>INFORMATIK</prüfungskomponente5>
    </kurs>
    <kurs id="11c">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>DEUTSCH</prüfungsfach4>
        <prüfungskomponente5>INFORMATIK</prüfungskomponente5>
    </kurs>
    <kurs id="11d">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>MATHEMATIK</prüfungsfach3>
        <prüfungsfach4>INFORMATIK</prüfungsfach4>
        <prüfungskomponente5>DEUTSCH</prüfungskomponente5>
    </kurs>
    <kurs id="11e">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>INFORMATIK</prüfungsfach3>
        <prüfungsfach4>MATHEMATIK</prüfungsfach4>
        <prüfungskomponente5>DEUTSCH</prüfungskomponente5>
    </kurs>
    <kurs id="11f">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>INFORMATIK</prüfungsfach3>
        <prüfungsfach4>DEUTSCH</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>

    <kurs id="12a">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>MATHEMATIK</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>
    <kurs id="12b">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>MATHEMATIK</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>
    <kurs id="12c">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>DEUTSCH</prüfungsfach3>
        <prüfungsfach4>BELIEBIG</prüfungsfach4>
        <prüfungskomponente5>MATHEMATIK</prüfungskomponente5>
    </kurs>
    <kurs id="12d">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>AFII</leistungskurs2>
        <prüfungsfach3>BELIEBIG</prüfungsfach3>
        <prüfungsfach4>DEUTSCH</prüfungsfach4>
        <prüfungskomponente5>BELIEBIG</prüfungskomponente5>
    </kurs>

    <kurs id="13a">
        <leistungskurs1>ENGLISCH</leistungskurs1>
        <leistungskurs2>MATHEMATIK</leistungskurs2>
        <prüfungsfach3>AFII</prüfungsfach3>
